import { Contact } from '../../platform/types';

export const INITIAL_CONTACTS: Contact[] = [
  {
    id: 'c-1',
    firstName: 'Alex',
    lastName: 'Johnson',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80',
    email: 'alex.johnson@driveosx.com',
    phone: '+1 (555) 234-5678',
    company: 'DriveOSX Technologies',
    jobTitle: 'Principal System Architect',
    department: 'Engineering',
    team: 'Core Kernel',
    address: '450 Innovation Way, San Francisco, CA 94105',
    website: 'https://alexjohnson.dev',
    birthday: '1990-04-15',
    notes: 'Key contact for operating system architecture & performance optimizations.',
    isFavorite: true,
    labels: ['Work', 'Tech Team', 'VIP'],
    organization: 'DriveOSX Corp',
    avatarBg: 'bg-gradient-to-br from-indigo-500 to-purple-600',
  },
  {
    id: 'c-2',
    firstName: 'Sarah',
    lastName: 'Miller',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=300&auto=format&fit=crop&q=80',
    email: 'sarah.miller@driveosx.com',
    phone: '+1 (555) 876-5432',
    company: 'DriveOSX Technologies',
    jobTitle: 'Head of Product Design',
    department: 'Design & UX',
    team: 'UI Systems',
    address: '100 Silicon Blvd, Suite 400, San Jose, CA 95113',
    website: 'https://sarahmiller.design',
    birthday: '1992-08-22',
    notes: 'Leads desktop theme guidelines & smooth motion animations.',
    isFavorite: true,
    labels: ['Work', 'Marketing', 'VIP'],
    organization: 'DriveOSX Corp',
    avatarBg: 'bg-gradient-to-br from-pink-500 to-rose-600',
  },
  {
    id: 'c-3',
    firstName: 'David',
    lastName: 'Chen',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    email: 'david.chen@cloudnet.io',
    phone: '+1 (555) 345-6789',
    company: 'CloudNet Infrastructure',
    jobTitle: 'VP of Infrastructure',
    department: 'Cloud Services',
    team: 'DevOps',
    address: '888 Tech Drive, Austin, TX 78701',
    website: 'https://cloudnet.io',
    birthday: '1988-11-03',
    notes: 'Handles backend API connectivity & cloud sync pipelines.',
    isFavorite: false,
    labels: ['Work', 'Tech Team'],
    organization: 'CloudNet Inc',
    avatarBg: 'bg-gradient-to-br from-blue-500 to-cyan-600',
  },
  {
    id: 'c-4',
    firstName: 'Emily',
    lastName: 'Davis',
    photo: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=300&auto=format&fit=crop&q=80',
    email: 'emily.davis@driveosx.com',
    phone: '+1 (555) 987-6543',
    company: 'DriveOSX Technologies',
    jobTitle: 'Senior Marketing Director',
    department: 'Marketing',
    team: 'Brand Strategy',
    address: '250 Market St, San Francisco, CA 94102',
    website: 'https://emilydavis.com',
    birthday: '1994-01-29',
    notes: 'Manages OS release announcements & press communications.',
    isFavorite: true,
    labels: ['Marketing', 'Work'],
    organization: 'DriveOSX Corp',
    avatarBg: 'bg-gradient-to-br from-amber-500 to-orange-600',
  },
  {
    id: 'c-5',
    firstName: 'Michael',
    lastName: 'Scott',
    photo: '',
    email: 'michael.scott@dundertech.com',
    phone: '+1 (555) 456-7890',
    company: 'Dunder Tech Solutions',
    jobTitle: 'Regional Manager',
    department: 'Sales',
    team: 'Enterprise Sales',
    address: '1725 Slough Avenue, Scranton, PA 18503',
    website: 'https://dundertech.com',
    birthday: '1975-03-15',
    notes: 'Always prefers phone calls for urgent client inquiries.',
    isFavorite: false,
    labels: ['Work', 'Personal'],
    organization: 'Dunder Tech',
    avatarBg: 'bg-gradient-to-br from-emerald-500 to-teal-600',
  },
  {
    id: 'c-6',
    firstName: 'Lisa',
    lastName: 'Wong',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
    email: 'lisa.wong@quantumlabs.ai',
    phone: '+1 (555) 678-9012',
    company: 'QuantumLabs AI',
    jobTitle: 'Lead AI Scientist',
    department: 'Research',
    team: 'Machine Intelligence',
    address: '700 Palo Alto Tech Park, Palo Alto, CA 94304',
    website: 'https://quantumlabs.ai',
    birthday: '1991-09-18',
    notes: 'Collaborating on native Gemini LLM desktop integration.',
    isFavorite: true,
    labels: ['Tech Team', 'VIP', 'Work'],
    organization: 'QuantumLabs AI Inc',
    avatarBg: 'bg-gradient-to-br from-violet-500 to-fuchsia-600',
  },
  {
    id: 'c-7',
    firstName: 'Carlos',
    lastName: 'Rodriguez',
    photo: '',
    email: 'carlos.r@familynet.org',
    phone: '+1 (555) 789-0123',
    company: 'Rodriguez Creative Studio',
    jobTitle: 'Creative Director',
    department: 'Design & UX',
    team: 'Media Arts',
    address: '120 Ocean Drive, Miami, FL 33139',
    website: 'https://carloscreative.co',
    birthday: '1987-06-12',
    notes: 'Family friend and consultant on digital photography projects.',
    isFavorite: false,
    labels: ['Family', 'Personal'],
    organization: 'Rodriguez Studio',
    avatarBg: 'bg-gradient-to-br from-red-500 to-rose-700',
  },
];
